### ISSUE TITLE
ResourceLoader

### ISSUE THREAD

**Issue by Cometary** [HyoungMinSong/wehagoreact#89]
## 문제

서버가 가동되는 동안 변화된 파일의 리소스를 서버를 재가동하지 않으면 인지하지 못하는 현상입니다.

## 실패

리소스 로딩을 상대경로에서 절대경로로 변경

AWS S3 버킷을 이용한 파일 저장(시간 관계상 중도 포기)

Devtool로 파일 변경 감지를 이용한 리로딩

## 해결

서버가 가동되는 동안 변화된 동적 리소스들을 저장시키고 임시로 출력하기 위해 `private static final Map<String, byte[]> *imageMap* = new HashMap<>();`와 같은 static 클래스를 만듭니다.

## 개선 방안

캐시로서 저장되므로 용량이 많아지면 서버에 부담이 가해집니다. 일정한 용량이나 시간이 지나면 캐시를 비워주는 방법이나 S3와 같은 외부 저장 경로를 이용하여 파일을 관리하는 것이 더 나은 방법일 것으로 생각됩니다.

**Comment by HyoungMinSong** [comment]
좋은 해결 방법 같습니다.
